### ISSUE TITLE
Oculus Rift controllers inactive

### ISSUE THREAD

**Issue by denisfitz57** [PRIMITIVE-IO/primitive#1]
**Summary**
I see the initial view, but the none of the buttons on the Touch controllers (except for the Oculus home key) are functioning (the controller icons are visible).
What's the problem?
see above
**Platform** (Vive, Rift, Windows MR, GearVR):  Oculus Rift
**Loaded project**: 
Unable to load anything
**What steps are needed to reproduce the issue?**
Start the program (that's it).
The log file is attached.
[output_log.txt](https://github.com/PRIMITIVE-IO/primitive/files/1718376/output_log.txt)

**Comment by atonalfreerider** [comment]
Thanks @denisfitz57 for the input - are you running your Rift on SteamVR? This is a requirement.
