### ISSUE TITLE
You can mark a method, but it's not documented.

### ISSUE THREAD

**Issue by brianpeiris** [PRIMITIVE-IO/primitive#10]
**Summary**

I discovered that you can mark a method by pressing left on the exploration wand. The method turns red and then a marker appears on the execution timeline. That's awesome! I wish it was documented so that I knew about it earlier.

**Platform** (Vive, Rift, Windows MR, GearVR): Vive

**Comment by atonalfreerider** [comment]
You discovered a hidden feature! Yes, pressing left on the touchpad sets a "breakpoint" in the runtime. You can select the red lines on the timeline to jump to the point in the execution where the marked method is called. We weren't quite ready to advertise this feature but we will soon.

**Comment by avik-das** [comment]
@brianpeiris: Awesome job finding this feature! [I documented it in the README.](https://github.com/PRIMITIVE-IO/primitive#setting-breakpoints)

Thanks for pointing this out.
