### ISSUE TITLE
The "Exit Package" action is misleading

### ISSUE THREAD

**Issue by brianpeiris** [PRIMITIVE-IO/primitive#12]
**Summary**

As far as I can tell, the "Exit Package" action doesn't actually collapse the package, as I would expect it to. It simply deselects the currently selected class. Maybe it should be renamed "Deselect Class" instead.

**Platform** (Vive, Rift, Windows MR, GearVR): Vive

**Comment by atonalfreerider** [comment]
Collapsing an open package is achieved by aiming at the root of the open package and pressing the "Collapse Package" button that appears on your controller.
