### ISSUE TITLE
Tedious navigation on GearVR

### ISSUE THREAD

**Issue by Zeukkari** [PRIMITIVE-IO/primitive#14]
**Summary**

What's the problem?

Navigation isn't really usable on GearVR (without accessories?). There should be a way to point and click teleport.

**Platform** (Vive, Rift, Windows MR, GearVR): 

GearVR

**Loaded project**: 

deeplearning4f

**What steps are needed to reproduce the issue?**

figure it out

**Comment by atonalfreerider** [comment]
Thanks for the feedback. If you hold down the touchpad for 3 seconds it will let you teleport to the point that you are looking at on the ground. This is documented in our readme:
https://github.com/PRIMITIVE-IO/primitive/blob/master/README.md

Our GearVR support is early but we appreciate your input.

**Comment by Zeukkari** [comment]
Cool, I read through the documentation looking for that but did not see it. I will retry after my device cools down.

I'm well aware that your GearVR support is early :)
