### ISSUE TITLE
How to open a custom project

### ISSUE THREAD

**Issue by kumavis** [PRIMITIVE-IO/primitive#18]
I'd like to open up my own project and visualize it in primitive. Its not immediately obvious how to do this.

**Comment by atonalfreerider** [comment]
Thanks for the question. This is currently not a feature in the alpha - we are only displaying a selection of demo codebases that we have analyzed. 

Analyzing your own project will be a capability you will have when we release the full version of Primitive.

**Comment by atonalfreerider** [comment]
Take a look at our plugins now available on IntelliJ IDEA and Visual Studio:
https://plugins.jetbrains.com/plugin/11587-primitive-vr-java-analyzer
https://marketplace.visualstudio.com/items?itemName=Primitive.PrimitiveVRCSharpAnalyzer

These will allow you to generate .analysis files that can be viewed from the "analyzed-programs" folder in the Primitive install location on your PC.
