### ISSUE TITLE
Consider allowing a direct download from your website

### ISSUE THREAD

**Issue by brianpeiris** [PRIMITIVE-IO/primitive#20]
**Summary**
I can't use Steam at work because it requires special UDP port access to login and my office firewall does not allow them. Also, I presume the VivePort distribution does not work with the Oculus Rift.

**Platform** (Vive, Rift, Windows MR, GearVR): 
Windows, Oculus Rift

**Comment by atonalfreerider** [comment]
Thanks @brianpeiris we've publicly released for non-commercial use. If you'd like to get a demo for work you can contact me directly and I can email you a demo.

Viveport now supports Rift: https://blog.vive.com/us/2018/09/04/play-oculus-rift-titles-via-viveport/

**Comment by brianpeiris** [comment]
Good to know, thanks. Congrats on the release!
