### ISSUE TITLE
No way to access runtime mode with Oculus

### ISSUE THREAD

**Issue by brianpeiris** [PRIMITIVE-IO/primitive#21]
**Summary**

It seems there's no way to access runtime mode using Oculus via the VivePort distribution. I'm viewing a project that seems to have a timeline, but buttons on the left controller do nothing.

![primitive_2019-01-24_13-07-06](https://user-images.githubusercontent.com/79419/51708667-5111dc00-1fd9-11e9-8d12-e92e31a18ead.png)

**Platform** (Vive, Rift, Windows MR, GearVR): 
Oculus Rift via VivePort

**Loaded project**: 
"gold"

**Comment by atonalfreerider** [comment]
The runtime is launchable from the "EXECUTE" tag that is attached to a class in the model. In this case: 
Service.GraphQLServiceTest

**Comment by brianpeiris** [comment]
Aha, thanks.
