### ISSUE TITLE
Valve Index Support

### ISSUE THREAD

**Issue by gabrieljones** [PRIMITIVE-IO/primitive#24]
**Summary**

I launched this on a Win10 PC with Steam. It loaded in 2D instead of in 3D in the HMD.

The HMD shows the Primitive logo while it is loading, but then i am left standing in the empty Steam env

**Platform** (Vive, Rift, Windows MR, GearVR): Valve Index
**Loaded project**: Any

**What steps are needed to reproduce the issue?**

1. Install via Steam
1. Launch via Steam
1. or Launch via Steam VR Home

**Comment by atonalfreerider** [comment]
Hi @gabrieljones thanks for your response. Our next build release (releasing on 8/4/2019) will support Index. Sorry for the inconvenience.
