### ISSUE TITLE
C# files are only partially loaded

### ISSUE THREAD

**Issue by dvdvorle** [PRIMITIVE-IO/primitive#26]
**Summary**

When viewing C# files the source is only loaded until the line containing the class keyword. This is consistent accross public and local repositories.

**Platform** (Vive, Rift, Windows MR, GearVR): 
Windows 10, Oculus Rift

**Loaded project**: 
Roslyn

**What steps are needed to reproduce the issue?**
Just open up any C# file
![CSharp-Primitive](https://user-images.githubusercontent.com/175623/79399606-1997a280-7f84-11ea-84ed-d7286171b38f.png)

**Comment by atonalfreerider** [comment]
Thanks @dvdvorle - this is intentional. If you press the "open" button on your VR controller it will open the rest of the file.

**Comment by dvdvorle** [comment]
Gotcha, going to read the docs better next time...
