### ISSUE TITLE
Unable to view my private repo/ open analysis in Primitive

### ISSUE THREAD

**Issue by f-gdovin** [PRIMITIVE-IO/primitive#28]
**Summary**

My use case is:
I want to _somehow_ visualise one of my projects.

***Here is what I tried (based on documentation):***

I tried Primitive on Meta Quest2, I was able to open the app and explore default project.
However, I was unable to switch to private repo using in-app menu
(I do not know where to get neither code, nor enrironment file),
so I decided to check IDE plugin to generate an analysis in order to view it in Primitive.

That's where I got stuck again.

***So I need to solve (at least one of) these problems:***

* how to connect to my private repo from within the app? I could not find any documentation and I don't understand in-app instructions (more details above)
* how to make 'Primitive VR Java Analyzer' work so that I can import an analysis of my project and view it?

**Platform** (Vive, Rift, Windows MR, GearVR):
VR: Meta Quest2 (Primitive app sideloaded via SideQuest)
PC (on which I tried to generate analysis):
* Win10 Pro 64Bit, AMD Ryzen 3800XT, 32GB RAM, NVMe SSD, newest IDEA
* Macbook 2019 Pro, newest MacOS Ventura, Intel i7 x86, 16GB RAM, SSD, newest IDEA

Tried on
**Loaded project**: 
several private repositories

**What steps are needed to reproduce the issue?**

1. install 'Primitive VR Java Analyzer' onto Intellij IDEA (I tried newest 2022.3 and slightly older 2022.1)
2. run 'Primitive -> Generate Static Analysis'
3. I see modal scanning classes, but then it crashes with:

`java.io.IOException: java.sql.SQLException: No suitable driver found for jdbc:sqlite:/var/folders/tk/ptd0d6ds4gzckt__f8ssfmyr0000gn/T/raw-analysise381eabc1769ad3b3a9dfd7c2e5f2bc70d593ced.db
	at io.primitive.intellij.output.SQLiteOutput.serialize(SQLiteOutput.kt:37)
	at io.primitive.intellij.task.GenerateStaticAnalysisTask.compute(GenerateStaticAnalysisTask.kt:75)
	at io.primitive.intellij.task.GenerateStaticAnalysisTask.compute(GenerateStaticAnalysisTask.kt:32)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:335)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
`

This error appears on both Win and Mac, regarless of project (I tried one massive and one small project, both Java (11, 17 respectively), I tried running IDEA with admin rights (on Win)

**Comment by atonalfreerider** [comment]
Thank you for taking all of these steps. We actually deprecated our IDE plugins for Visual Studio and IDEA. I think we'll remove them from the plugin stores to avoid future confusion.

If you send an email to support@primitive.io we'll send you a personalized invite code to our new cloud server that you can connect your github, bitbucket, or gitlab account to. The server will provide a one time pin that you can enter in your Quest to see your code.

**Comment by f-gdovin** [comment]
Thank you for quick reply.

I wrote you guys an email so hopefully we will sort this out.

I think that your documentation is seriously outdated and plugins should definitely be removed/updated with some disclaimer, as there are few articles on the web mentioning them, yet they no longer work.
