### ISSUE TITLE
Labels for Oculus Touch controls disappear in controller model when using the Rift via SteamVR

### ISSUE THREAD

**Issue by brianpeiris** [PRIMITIVE-IO/primitive#8]
**Summary**
The label pointers disappear into the controller model, so it's difficult to tell exactly what the label is pointing to. 

![image](https://user-images.githubusercontent.com/79419/36771442-57829b66-1c05-11e8-8abf-cc08dddc4a76.png)

**Platform** (Vive, Rift, Windows MR, GearVR): Oculus Rift via SteamVR

**Comment by tnterdan** [comment]
@brianpeiris We've just released a new version on Steam and the Oculus stores, in which the tooltip lines are no longer clipping completely into the controller. I am always looking for ways to improve the tooltips; thank you for the feedback!
