### ISSUE TITLE
Controller movement is choppy when moving over and scrolling source code

### ISSUE THREAD

**Issue by brianpeiris** [PRIMITIVE-IO/primitive#9]
**Summary**
There are perceptible jumps when moving the exploration wand over source code and when scrolling it. The physical disconnect is actually a bit nauseating.

**Platform** (Vive, Rift, Windows MR, GearVR): Vive

**Comment by tnterdan** [comment]
@brianpeiris We've just released a new version on the Steam and Oculus stores. The new version uses a smoother raycasting algorithm, which should eliminate any choppiness when scrolling. Thanks again for the feedback :)

**Comment by brianpeiris** [comment]
It's a lot better now! Thanks
